import time

from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

from webdriver_manager.chrome import ChromeDriverManager

options=webdriver.ChromeOptions()
options.add_experimental_option(name="detach",value=True)       #using this statement to stable the browser (not close automatically)
s=Service('C:\\Users\\somesh.rai_infobeans\\Documents\\Driver\\chromedriver.exe')
driver=webdriver.Chrome(options=options,service=s)
# driver.get("https://toolsqa.com/selenium-training?q=banner#enroll-form")
# driver.maximize_window()
# time.sleep(2)
# driver.find_element("xpath","//input[@id='first-name']").send_keys("Fname")
# driver.find_element("xpath","//input[@id='last-name']").send_keys("Lname")
# driver.find_element("xpath","//input[@id='email']").send_keys("email@email.com")
# driver.find_element("xpath","//input[@id='mobile']").send_keys("0123456789")
# x=driver.find_element("xpath","//select[@name='country']")
# sel=Select(x)
# sel.select_by_visible_text("Afghanistan")
# driver.find_element("xpath","//input[@id='city']").send_keys("city")
# driver.find_element("xpath","//textarea[@class='upcoming__registration--input']").send_keys("Input message")
# time.sleep(10)
# driver.find_element("xpath","//button[@class='btn btn-block btn-primary']").click()
# # border=driver.find_element("xpath","//div[contains(text(),'We have received your message. We will soon get in touch.')]")
# # print(border.text)

# driver.get("https://blazedemo.com/")
# driver.maximize_window()
# time.sleep(2)
# departurecity=driver.find_element("xpath","//select[@name='fromPort']")
# sel=Select(departurecity)
# sel.select_by_visible_text("Philadelphia")
# destinationcity=driver.find_element("xpath","//select[@name='toPort']")
# sel1=Select(destinationcity)
# sel1.select_by_visible_text("Rome")
# driver.find_element("xpath","//input[@class='btn btn-primary']").click()
# time.sleep(3)
# driver.find_element("xpath","(//input[@class='btn btn-small'])[2]").click()
# time.sleep(3)
# Flight=driver.find_element("xpath","(//div[@class='container'])[2]")
# print(Flight.text)
# driver.find_element("xpath","//input[@id='inputName']").send_keys("Somesh")
# driver.find_element("xpath","//input[@id='address']").send_keys("Address")
# driver.find_element("xpath","//input[@id='city']").send_keys("city")
# driver.find_element("xpath","//input[@id='state']").send_keys("California")
# driver.find_element("xpath","//input[@id='zipCode']").send_keys("345262")
# driver.find_element("xpath","//input[@id='creditCardNumber']").send_keys("37473747345345345")
# driver.find_element("xpath","//input[@id='creditCardMonth']").send_keys("03")
# driver.find_element("xpath","//input[@id='creditCardYear']").send_keys("2024")
# driver.find_element("xpath","//input[@id='nameOnCard']").send_keys("USA")
# cardtype=driver.find_element("xpath","//select[@class='form-inline']")
# sel2=Select(cardtype)
# sel2.select_by_visible_text("American Express")
# time.sleep(2)
# driver.find_element("xpath","//input[@type='checkbox']").click()
# driver.find_element("xpath","//input[@class='btn btn-primary']").click()
# time.sleep(3)
# purchase=driver.find_element("xpath","//div[@class='container hero-unit']")
# print(purchase.text)


driver.get("https://demoqa.com/alertsWindows")
time.sleep(5)
driver.maximize_window()
time.sleep(4)
driver.find_element("xpath","//span[text()='Alerts']").click()
time.sleep(3)
alert=driver.find_element("xpath","//button[@id='alertButton']")
time.sleep(3)
alert.click()
a=ActionChains(driver)
al=Alert(driver)
time.sleep(4)
print(al.text)
al.accept()
btn1=driver.find_element("xpath","//button[@id='confirmButton']")
time.sleep(3)
btn1.click()
#al.accept()
print(al.text)
al.dismiss()
alertpromt = driver.find_element("xpath","//button[@id='promtButton']")
time.sleep(2)
alertpromt.click()
al.send_keys("promt message")

# driver.find_element("xpath","//div[text()='Elements']").click()
# time.sleep(2)
# driver.find_element("xpath","//span[text()='Check Box']").click()
# time.sleep(2)
# driver.find_element("xpath","//span[@class='rct-checkbox']").click()
# time.sleep(3)